version: '3.4'

services:
  egdebookingsystem:
    image: ${DOCKER_REGISTRY-}egdebookingsystem
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8000:80"
    depends_on:
        - db
  db:
     image: "microsoft/mssql-server-linux"
     environment:
         SA_PASSWORD: "Password123@"
         ACCEPT_EULA: "Y"